export const RESUME_DATA = {
  profile: {
    name: 'Jainil Deven Mehta',
    role: 'Software Engineer',
    headline: 'Engineering Scalable Solutions',
    short_pitch:
      'Frontend Software Engineer with 2.5+ years of experience building enterprise SaaS applications and modern web interfaces. Skilled in React.js, TypeScript, JavaScript, and Angular, with expertise in component architecture, REST API integration, frontend performance optimization, and accessible UI development aligned with WCAG 2.1 and Section 508 standards.',
    email: 'jainil237@gmail.com',
    location: 'Ahmedabad, India',
    summary:
      'Frontend Software Engineer with 2.5+ years of experience building enterprise SaaS applications and modern web interfaces. Skilled in React.js, TypeScript, JavaScript, and Angular, with expertise in component architecture, REST API integration, frontend performance optimization, and accessible UI development aligned with WCAG 2.1 and Section 508 standards.',
    avatar:
      'https://api.dicebear.com/7.x/avataaars/svg?seed=Jainil&backgroundColor=18181b&clothing=blazerAndShirt&eyes=happy&skinColor=light',
    linkedin: 'https://www.linkedin.com/in/jainil-mehta-5b83a1183/',
    github: 'https://github.com/jainil237',
    medium: 'https://medium.com/@jainil237',
  },
  skills: [
    {
      name: 'Frontend',
      items: ['React.js', 'Next.js', 'Angular', 'Redux', 'NgRx', 'RxJS', 'Signals', 'Angular Material', 'HTML', 'CSS'],
    },
    {
      name: 'Backend',
      items: ['Node.js', 'Express.js', 'NestJS', 'REST APIs', 'Sequelize', 'AWS S3', 'AWS Lambda', 'EC2', 'Cognito'],
    },
    { name: 'Databases', items: ['PostgreSQL', 'MongoDB', 'MySQL', 'Firebase'] },
    { name: 'Coding Languages', items: ['TypeScript', 'JavaScript', 'Python', 'Java', 'C++', 'C'] },
    {
      name: 'AI, Tools & Practices',
      items: ['Git', 'BitBucket', 'Jira', 'Agile/Scrum', 'CI/CD', 'OpenAI API', 'Claude Code', 'Mixpanel'],
    },
  ],
  experience: [
    {
      id: 'job-1',
      type: 'experience' as const,
      title: 'Software Engineer',
      subtitle: 'ARInspect - A Unit of Tyler Technologies',
      date: 'Jan 2023 - May 2025',
      location: 'Ahmedabad, India',
      description:
        'Spearheaded the migration to Angular v16 and engineered enterprise-grade web modules.',
      details: [
        'Shipped production frontend features for ARInspect, an enterprise GovTech platform supporting environmental compliance and inspection workflows, collaborating with Product, Design, QA, and Backend teams in Agile sprints.',
        'Developed a React-based proof of concept to evaluate component-driven architecture, reusable UI patterns, and frontend scalability for future product initiatives.',
        'Refactored legacy frontend modules into a modular MVVM-based architecture by introducing reusable component patterns and a centralized custom state management solution inspired by Redux principles, improving maintainability and predictable state updates.',
        'Modernized the application by contributing to the migration from Angular v10 to Angular v16, while developing reusable, accessible UI components aligned with WCAG 2.1 and Section 508 standards.',
        'Developed and optimized RESTful APIs using Node.js, Sequelize, and PostgreSQL, enabling seamless frontend integration for data-intensive enterprise workflows.',
        'Integrated Mixpanel analytics to capture user behavior and support data-driven product improvements, while contributing to production stability through debugging, code reviews, and cross-functional release support.',
      ],
      tags: [
        'Angular',
        'RxJS',
        'Node.JS',
        'Material Angular',
        'OpenAI API',
        'React',
        'Mixpanel',
        'WCAG 2.1',
      ],
    },
    {
      id: 'job-2',
      type: 'experience' as const,
      title: 'Software Engineer Intern',
      subtitle: 'DXFactor',
      date: 'Jul 2022 – Dec 2022',
      location: 'Ahmedabad, India',
      description:
        'Developed responsive dashboards and RESTful APIs to enhance business decision-making.',
      details: [
        'Developed responsive Angular dashboards for visualization and analysis of business KPIs.',
        'Built .NET Core Web APIs supporting enterprise dashboard functionality, with emphasis on reusable endpoints and maintainable backend application architecture.',
        'Implemented dynamic filtering, search functionality, and optimized data views to improve application responsiveness and data-access efficiency.',
      ],
      tags: ['Angular', '.NET Core Web API', 'RESTful APIs'],
    },
  ],
  education: [
    {
      id: 'edu-1',
      type: 'education' as const,
      title: 'BE in Computer Engineering',
      subtitle: 'LDRP Institute of Technology and Research',
      date: '2018 - 2022',
      location: 'Gandhinagar, India',
      description:
        'Graduated with 8.02 CGPA. Focused on Core CS fundamentals and Full Stack Development.',
      details: [
        'Achieved a CGPA of 8.02.',
        'Relevant Coursework: Data Structures & Algorithms, Database Management Systems, Operating Systems, Object-Oriented Programming.',
        'Secured AIR 5355 in GATE 2022 CS-IT paper',
      ],
      tags: [
        'Data Structures',
        'Operating Systems',
        'Object-Oriented Programming',
        'Database Management Systems',
        'Web Development',
        'Java',
        'C++',
        'C',
      ],
    },
  ],
  projects: [
    {
      type: 'project',
      title: 'E-Commerce Platform',
      category: 'Full-Stack Monorepo',
      tech: 'Next.js • TypeScript • Node.js • PostgreSQL • Redis',
      desc: 'Full-stack e-commerce monorepo sharing pages and logic across buyer and admin apps, with concurrency-safe inventory, payments, and queue-backed notifications.',
      details: [
        'Built a full-stack e-commerce monorepo (Next.js, TypeScript, Node.js, Express.js, PostgreSQL) sharing pages and logic across buyer and admin apps.',
        'Implemented an inventory reservation system that holds stock at order creation and converts it at payment, with row-level locking to prevent overselling under concurrent orders.',
        'Implemented BullMQ workers backed by Redis for email, OTP, and shipping notifications, with retry handling and fallback execution to keep request flows resilient.',
        'Implemented Redis-backed caching for product/category APIs and rate limiting, with in-memory fallbacks to preserve availability during Redis outages.',
        'Integrated third-party payment processing with webhook-driven order updates, automated invoice PDF generation, and concurrency-safe coupon redemption using atomic guards and unique constraints.',
      ],
      tags: [
        'Next.js',
        'TypeScript',
        'Node.js',
        'Express.js',
        'PostgreSQL',
        'Redis',
        'BullMQ',
      ],
      webSiteLink: 'https://jainil-mystore.vercel.app/',
    },
    {
      type: 'project',
      title: 'Olive Audio Lab',
      category: 'Content Management Platform',
      tech: 'React • Firebase • Shadcn UI • Tailwind',
      desc: 'Full-stack content management platform for artists and music discography, with real-time sync and role-based admin publishing.',
      details: [
        'Built a full-stack content management platform for artists and music discography, using React and Firebase for real-time data sync and role-based (admin) content publishing, including song/artist CRUD, dynamic forms, and embedded track players.',
        'Developed a reusable component library with Shadcn UI and Tailwind CSS, delivering a fully responsive design and reducing per-feature UI development time.',
        'Ran a Lighthouse-driven performance pass and deployed the app live on Vercel.',
      ],
      tags: ['React.js', 'Firebase', 'Shadcn UI', 'Tailwind CSS', 'Vercel'],
      webSiteLink: 'https://olive-audio-lab.vercel.app/',
      link: 'https://github.com/jainil237/olive-audio-lab',
    },
    {
      type: 'project',
      title: 'Big Moves Entertainment',
      category: 'Marketing Website',
      tech: 'Next.js • TypeScript • Tailwind • Vercel',
      desc: 'Marketing site for a creative production studio offering sonic branding, video production, and music marketing under one creative direction.',
      details: [
        'Built the marketing website for Big Moves Entertainment, a creative production studio covering sonic branding, video production, and music marketing.',
        'Developed service pages for jingles and sonic branding, video production, and artist growth marketing, structured around a single conversion path.',
        'Implemented conversion-focused CTAs including strategy-call booking, WhatsApp contact, and inquiry forms across the site.',
        'Optimized media-heavy pages with Next.js image optimization and responsive layouts for fast loads across devices, deployed on Vercel.',
      ],
      tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Responsive Design', 'Vercel'],
      webSiteLink: 'https://bigmoves-ent.vercel.app/',
    },
    {
      type: 'project',
      title: 'Augmented Field Operations (AFO) Platform',
      category: 'GovTech Platform',
      tech: 'Angular • Node.js • PostgreSQL • React.js • AWS',
      desc: 'Contributed to a GovTech platform used by US agencies for environmental monitoring, compliance, and inspection workflows.',
      details: [
        'Contributed to a GovTech platform used by US agencies for environmental monitoring, compliance, and inspection workflows.',
        'Delivered PWA online/offline sync and key modules including inspections, violations, attachments, and location management.',
        'Implemented Section 508 accessibility compliance, improving usability and aligning with regulatory standards.',
        'Supported production releases and sprint delivery, ensuring system stability and timely feature rollout.',
      ],
      tags: ['Angular', 'Node.js', 'PostgreSQL', 'React.js', 'Section 508', 'AWS'],
    },
  ],
  awards: [
    {
      title: 'SPOT Award',
      org: 'ARInspect',
      date: 'Aug 2023',
      desc: 'Recognized for delivering a critical ETL solution that met client specifications, optimized data pipelines, and ensured on-time product delivery through effective cross-functional collaboration.',
      link: '',
    },
    {
      title: 'Governor Scout Award',
      org: 'Rajya Puraskar',
      date: 'Feb 2015',
      desc: 'Highest state-level scouting honor awarded by the State Governor for outstanding achievement in leadership and community service.',
      link: '',
    },
  ],
  certificates: [
    {
      title: 'IBM Full Stack Software Developer',
      org: 'IBM',
      date: '',
      link: 'https://coursera.org/share/c5155c006c4d0f8d9559c3a14be2a2f3',
    },
    {
      title: 'Intro to TensorFlow for AI/ML/DL',
      org: 'DeepLearning.AI',
      date: '',
      link: 'https://coursera.org/share/ba18b5227e19d8d51d2c989468817360',
    },
    {
      title: 'Programming Foundations: JS, HTML, CSS',
      org: 'Coursera',
      date: '',
      link: 'https://coursera.org/share/2ecb4fae78477f74c26bf83becddbefe',
    },
    {
      title: 'McKinsey.org Forward Program',
      org: 'McKinsey & Company',
      date: '',
      link: 'https://www.credly.com/badges/e1a23e7d-c10d-4662-8f1f-99a8984d4f6d/public_url',
    },
  ],
};
