export const RESUME_DATA = {
  profile: {
    name: 'Jainil Deven Mehta',
    role: 'Full-Stack Engineer',
    headline: 'Engineering Scalable Solutions',
    short_pitch:
      "Hi, I'm Jainil Mehta. I'm a Full-Stack Software Engineer specializing in the Angular & Node.js ecosystem. I transform complex requirements into high-performance, accessible web applications.",
    email: 'jainil237@gmail.com',
    location: 'Ahmedabad, India',
    summary:
      'Full-Stack Software Engineer with 2.5 years of experience in Angular, Node.js, React, Java, and PostgreSQL. Skilled in building scalable web applications and developing RESTful APIs. Experienced in integrating AI/LLM solutions with OpenAI APIs and collaborating with cross-functional teams to deliver high-performance, user-focused software.',
    avatar:
      'https://api.dicebear.com/7.x/avataaars/svg?seed=Jainil&backgroundColor=18181b&clothing=blazerAndShirt&eyes=happy&skinColor=light',
    linkedin: 'https://www.linkedin.com/in/jainil-mehta-5b83a1183/',
    github: 'https://github.com/jainil237',
    medium: 'https://medium.com/@jainil237',
  },
  skills: [
    {
      name: 'Frontend',
      items: ['Angular', 'RxJS', 'NgRx', 'Signals', 'Material-Angular', 'React.js', 'Next.js','CSS'],
    },
    { name: 'Backend', items: ['Node.js', 'Express.js','NestJS', 'REST APIs', 'Sequelize','AWS'] },
    { name: 'Databases', items: ['PostgreSQL', 'MongoDB','MySQL'] },
    { name: 'Coding Languages', items: ['TypeScript', 'JavaScript', 'Java', 'C++', 'C'] },
  ],
  experience: [
    {
      id: 'job-1',
      type: 'experience' as const,
      title: 'Software Engineer',
      subtitle: 'ARInspect - A Unit of Tyler Technologies',
      date: 'Jan 2023 - May 2025',
      location: 'Ahmedabad, India',
      description:
        'Spearheaded the migration to Angular v16 and engineered enterprise-grade web modules.',
      details: [
        'Delivered scalable frontend features using Angular v16 TypeScript, and RxJS, collaborating cross-functionally with Product, Design, QA, and Backend teams to ship production-ready features in Agile sprints.',
        'Contributed to Angular v10 to v16 migration, improving code maintainability, reducing technical debt, and aligning the application with modern Angular standards.',
        'Refactored legacy UI modules into a modular MVVM-based architecture, improving code readability and enabling faster feature development across modules.',
        'Developed reusable Angular Material components and standardized UI patterns adhering to WCAG 2.1 and Section 508 accessibility standards, ensuring accessible user experiences while reducing UI duplication and improving development efficiency.',
        'Developed and optimized RESTful APIs using Node.js and Sequelize with PostgreSQL, improving query efficiency and ensuring reliable backend performance for data-intensive workflows.',
        'Integrated Mixpanel analytics to track user interactions and feature usage, enabling data-driven insights for product decisions and UX improvements.',
        'Supported production stability and release cycles by debugging critical issues, participating in code reviews, and collaborating with QA/DevOps to ensure smooth deployments.',
        'Developed a React-based POC to evaluate alternative frontend approaches, analyzing trade-offs in performance, reusability, and scalability for future architecture decisions.',
      ],
      tags: [
        'Angular',
        'RxJS',
        'Node.JS',
        'Material Angular',
        'OpenAI API',
        'React',
        'Mixpanel',
        'WCAG 2.1',
      ],
    },
    {
      id: 'job-2',
      type: 'experience' as const,
      title: 'Software Engineer Intern',
      subtitle: 'DXFactor',
      date: 'Jul 2022 – Dec 2022',
      location: 'Ahmedabad, India',
      description:
        'Developed responsive dashboards and RESTful APIs to enhance business decision-making.',
      details: [
        'Developed responsive Angular dashboards using AmCharts to visualize business KPIs, enabling structured data analysis and reporting workflows.',
        'Built .NET Core Web APIs to support dashboard functionalities, focusing on reusable endpoint design, efficient data handling, and maintainable backend architecture.',
        'Implemented dynamic filtering, search capabilities, and optimized data views, improving data retrieval efficiency and enhancing overall system responsiveness.',
      ],
      tags: ['Angular', 'AmCharts', '.NET Core Web API', 'RESTful APIs'],
    },
  ],
  education: [
    {
      id: 'edu-1',
      type: 'education' as const,
      title: 'BE in Computer Engineering',
      subtitle: 'LDRP Institute of Technology and Research',
      date: '2018 - 2022',
      location: 'Gandhinagar, India',
      description:
        'Graduated with 8.02 CGPA. Focused on Core CS fundamentals and Full Stack Development.',
      details: [
        'Achieved a CGPA of 8.02.',
        'Relevant Coursework: Data Structures & Algorithms, Database Management Systems, Operating Systems, Object-Oriented Programming.',
        'Secured AIR 5355 in GATE 2022 CS-IT paper',
      ],
      tags: [
        'Data Structures',
        'Operating Systems',
        'Object-Oriented Programming',
        'Database Management Systems',
        'Web Development',
        'Java',
        'C++',
        'C',
      ],
    },
  ],
  projects: [
    {
      type: 'project',
      title: 'Augmented Field Operations (AFO) Platform',
      category: 'GovTech Platform',
      tech: 'Angular • Node.js • PostgreSQL • React.js • AWS',
      desc: 'Contributed to a GovTech platform used by US agencies for environmental monitoring, compliance, and inspection workflows.',
      details: [
        'Contributed to a GovTech platform used by US agencies for environmental monitoring, compliance, and inspection workflows.',
        'Delivered PWA online/offline sync and key modules including inspections, violations, attachments, and location management.',
        'Implemented Section 508 accessibility compliance, improving usability and aligning with regulatory standards.',
        'Supported production releases and sprint delivery, ensuring system stability and timely feature rollout.',
      ],
      tags: ['Angular', 'Node.js', 'PostgreSQL', 'React.js', 'Section 508', 'AWS'],
    },
    {
      type: 'project',
      title: 'Dynamic Inspection Template Builder',
      category: 'Template Management System',
      tech: 'Angular • JSON Schema • Node.js',
      desc: 'Built a low-code template management system using JSON schema to enable dynamic inspection form creation.',
      details: [
        'Built a low-code template management system using JSON schema to enable dynamic inspection form creation.',
        'Enabled real-time preview and validation, improving usability and reducing configuration errors.',
        'Reduced developer dependency, accelerating template updates and improving operational efficiency.',
      ],
      tags: ['Angular', 'JSON Schema', 'Node.js'],
    },
    {
      type: 'project',
      title: 'Olive Audio Lab',
      category: 'Web Application',
      tech: 'React • Firebase • Tailwind',
      desc: 'Developed a web application with React and Firebase-backed content management system for artists and discography. Built reusable, performance-optimized UI components using Tailwind CSS.',
      details: [
        'Developed a web application with React and Firebase-backed content management system for artists and discography.',
        'Built reusable, performance-optimized UI components using Tailwind CSS, ensuring fast load times and responsive design across devices.',
      ],
      tags: ['React.js', 'Firebase', 'Tailwind CSS'],
      webSiteLink: 'https://olive-audio-lab.vercel.app/',
      link: 'https://github.com/jainil237/olive-audio-lab',
    },
  ],
  awards: [
    {
      title: 'SPOT Award',
      org: 'ARInspect',
      date: 'Aug 2023',
      desc: 'Optimized ETL processes ensuring timely delivery.',
      link: '',
    },
    {
      title: 'Governor Scout Award',
      org: 'Rajya Puraskar',
      date: 'Feb 2015',
      desc: 'Highest state-level honor for Scouts.',
      link: '',
    },
  ],
  certificates: [
    {
      title: 'IBM Full Stack Software Developer',
      org: 'IBM',
      date: '',
      link: 'https://coursera.org/share/c5155c006c4d0f8d9559c3a14be2a2f3',
    },
    {
      title: 'Intro to TensorFlow for AI/ML/DL',
      org: 'DeepLearning.AI',
      date: '',
      link: 'https://coursera.org/share/ba18b5227e19d8d51d2c989468817360',
    },
    {
      title: 'Programming Foundations: JS, HTML, CSS',
      org: 'Coursera',
      date: '',
      link: 'https://coursera.org/share/2ecb4fae78477f74c26bf83becddbefe',
    },
    {
      title: 'McKinsey.org Forward Program',
      org: 'McKinsey & Company',
      date: '',
      link: 'https://www.credly.com/badges/e1a23e7d-c10d-4662-8f1f-99a8984d4f6d/public_url',
    },
  ],
};
